version: '3.5'

volumes:
  crouton_data:
services:
  music:
    image: yourfavoritekyle/crouton_bot_music
    container_name: bot-music
    environment:
      - TOKEN=${BOT_TOKEN}
    volumes:
      - crouton_data:/home
  standard:
    build:
      context: .
      dockerfile: standard.Dockerfile
    image: yourfavoritekyle/crouton_bot_standard
    container_name: bot-standard
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
    volumes:
      - crouton_data:/home
    command: npm run start
